# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd0e9b0b89826a81094e7e89f77c9b8a235ff58fb1b58346ee240a7f67fe621f5d85dbefe7b9ecb1f7819031e2c4f2c77a5c986800705192840f063cdd49f8af

test:
  secret_key_base: fde5ff693c3d3f92da9e2c64755fc0722d7bf9fd33b91ce6a221d2ed835a5b84e3a479e417f9b135dade1802e976d8a17654f7a8429aa8dfd348597e5675fac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
